Medical institution
srbulovicdusan/vivifyPraksa pull request #3
Opened 2020-01-16 09:23 UTC by srbulovicdusan

2020-01-16 10:24 UTC, milos996 commented on javascript/.cache/04/3a27fbb42a4f239a24cf4687413979.json
> +{"id":"anonymous.js","dependencies":[{"name":"/Users/dsrbulovic/workspace/vivifyPraksa/vivifyPraksa/javascript/package.json","includedInParent":true,"mtime":1579086788095}],"generated":{"js":"\"use s
obrisi prvo cache i node_modeuls iz javascript, kreiraj gitignore i odradi ono sa rm -rf cached . pa me onda cimaj opet , preveliki je diff za gledanje

2020-01-16 10:49 UTC, srbulovicdusan commented
Vazi, otisao sam da pojedem nesto pa kad se vratim odradicu to i mozemo da
prodiskutujemo o projektu

On Thu, Jan 16, 2020, 11:24 Milos Ivankovic <notifications@github.com>
wrote:

> *@milos996* commented on this pull request.
> ------------------------------
>
> In javascript/.cache/04/3a27fbb42a4f239a24cf4687413979.json
> <https://github.com/srbulovicdusan/vivifyPraksa/pull/3#discussion_r367339827>
> :
>
> > @@ -0,0 +1 @@
> +{"id":"anonymous.js","dependencies":[{"name":"/Users/dsrbulovic/workspace/vivifyPraksa/vivifyPraksa/javascript/package.json","includedInParent":true,"mtime":1579086788095}],"generated":{"js":"\"use strict\";\n\nObject.defineProperty(exports, \"__esModule\", {\n  value: true\n});\nexports.default = void 0;\n\nvar _default = function _default() {\n  var a = function a(arr) {\n    return arr.map(function (el) {\n      return el * el;\n    });\n  };\n\n  console.log(a([1, 2, 3]));\n\n  (function (a, b) {\n    var c = a + b;\n    console.log(c);\n  })(2, 4);\n\n  var timesTwo = function timesTwo(number) {\n    return number * 2;\n  };\n\n  console.log(timesTwo(4));\n};\n\nexports.default = _default;"},"sourceMaps":{"js":{"mappings":[{"generated":{"line":8,"column":15},"source":"anonymous.js","original":{"line":1,"column":15}},{"generated":{"line":8,"column":35},"source":"anonymous.js","original":{"line":1,"column":20}},{"generated":{"line":9,"column":0},"source":"anonymous.js","original":{"line":2,"column":4}},{"name":"a","generated":{"line":9,"column":6},"source":"anonymous.js","original":{"line":2,"column":8}},{"generated":{"line":9,"column":7},"source":"anonymous.js","original":{"line":2,"column":9}},{"generated":{"line":9,"column":10},"source":"anonymous.js","original":{"line":2,"column":12}},{"name":"a","generated":{"line":9,"column":19},"source":"anonymous.js","original":{"line":2,"column":8}},{"generated":{"line":9,"column":20},"source":"anonymous.js","original":{"line":2,"column":12}},{"name":"arr","generated":{"line":9,"column":21},"source":"anonymous.js","original":{"line":2,"column":21}},{"generated":{"line":9,"column":24},"source":"anonymous.js","original":{"line":2,"column":12}},{"generated":{"line":9,"column":26},"source":"anonymous.js","original":{"line":2,"column":25}},{"generated":{"line":10,"column":0},"source":"anonymous.js","original":{"line":3,"column":8}},{"name":"arr","generated":{"line":10,"column":11},"source":"anonymous.js","original":{"line":3,"column":15}},{"generated":{"line":10,"column":14},"source":"anonymous.js","original":{"line":3,"column":18}},{"name":"map","generated":{"line":10,"column":15},"source":"anonymous.js","original":{"line":3,"column":19}},{"generated":{"line":10,"column":18},"source":"anonymous.js","original":{"line":3,"column":15}},{"generated":{"line":10,"column":19},"source":"anonymous.js","original":{"line":3,"column":23}},{"name":"el","generated":{"line":10,"column":29},"source":"anonymous.js","original":{"line":3,"column":23}},{"generated":{"line":10,"column":31},"source":"anonymous.js","original":{"line":3,"column":25}},{"generated":{"line":11,"column":0},"source":"anonymous.js","original":{"line":3,"column":25}},{"name":"el","generated":{"line":11,"column":13},"source":"anonymous.js","original":{"line":3,"column":30}},{"generated":{"line":11,"column":15},"source":"anonymous.js","original":{"line":3,"column":32}},{"name":"el","generated":{"line":11,"column":18},"source":"anonymous.js","original":{"line":3,"column":33}},{"generated":{"line":11,"column":20},"source":"anonymous.js","original":{"line":3,"column":25}},{"generated":{"line":12,"column":0},"source":"anonymous.js","original":{"line":3,"column":25}},{"generated":{"line":12,"column":5},"source":"anonymous.js","original":{"line":3,"column":15}},{"generated":{"line":12,"column":6},"source":"anonymous.js","original":{"line":3,"column":8}},{"generated":{"line":13,"column":0},"source":"anonymous.js","original":{"line":4,"column":5}},{"generated":{"line":13,"column":3},"source":"anonymous.js","original":{"line":2,"column":4}},{"name":"console","generated":{"line":15,"column":0},"source":"anonymous.js","original":{"line":5,"column":4}},{"name":"console","generated":{"line":15,"column":2},"source":"anonymous.js","original":{"line":5,"column":4}},{"generated":{"line":15,"column":9},"source":"anonymous.js","original":{"line":5,"column":11}},{"name":"log","generated":{"line":15,"column":10},"source":"anonymous.js","original":{"line":5,"column":12}},{"generated":{"line":15,"column":13},"source":"anonymous.js","original":{"line":5,"column":4}},{"name":"a","generated":{"line":15,"column":14},"source":"anonymous.js","original":{"line":5,"column":16}},{"generated":{"line":15,"column":15},"source":"anonymous.js","original":{"line":5,"column":17}},{"generated":{"line":15,"column":16},"source":"anonymous.js","original":{"line":5,"column":18}},{"generated":{"line":15,"column":17},"source":"anonymous.js","original":{"line":5,"column":19}},{"generated":{"line":15,"column":18},"source":"anonymous.js","original":{"line":5,"column":18}},{"generated":{"line":15,"column":20},"source":"anonymous.js","original":{"line":5,"column":22}},{"generated":{"line":15,"column":21},"source":"anonymous.js","original":{"line":5,"column":18}},{"generated":{"line":15,"column":23},"source":"anonymous.js","original":{"line":5,"column":25}},{"generated":{"line":15,"column":24},"source":"anonymous.js","original":{"line":5,"column":18}},{"generated":{"line":15,"column":25},"source":"anonymous.js","original":{"line":5,"column":17}},{"generated":{"line":15,"column":26},"source":"anonymous.js","original":{"line":5,"column":4}},{"generated":{"line":17,"column":0},"source":"anonymous.js","original":{"line":6,"column":4}},{"generated":{"line":17,"column":3},"source":"anonymous.js","original":{"line":6,"column":5}},{"name":"a","generated":{"line":17,"column":13},"source":"anonymous.js","original":{"line":6,"column":14}},{"generated":{"line":17,"column":14},"source":"anonymous.js","original":{"line":6,"column":5}},{"name":"b","generated":{"line":17,"column":16},"source":"anonymous.js","original":{"line":6,"column":17}},{"generated":{"line":17,"column":17},"source":"anonymous.js","original":{"line":6,"column":5}},{"generated":{"line":17,"column":19},"source":"anonymous.js","original":{"line":6,"column":19}},{"generated":{"line":18,"column":0},"source":"anonymous.js","original":{"line":7,"column":8}},{"name":"c","generated":{"line":18,"column":8},"source":"anonymous.js","original":{"line":7,"column":12}},{"generated":{"line":18,"column":9},"source":"anonymous.js","original":{"line":7,"column":13}},{"name":"a","generated":{"line":18,"column":12},"source":"anonymous.js","original":{"line":7,"column":16}},{"generated":{"line":18,"column":13},"source":"anonymous.js","original":{"line":7,"column":17}},{"name":"b","generated":{"line":18,"column":16},"source":"anonymous.js","original":{"line":7,"column":20}},{"generated":{"line":18,"column":17},"source":"anonymous.js","original":{"line":7,"column":8}},{"name":"console","generated":{"line":19,"column":0},"source":"anonymous.js","original":{"line":8,"column":8}},{"name":"console","generated":{"line":19,"column":4},"source":"anonymous.js","original":{"line":8,"column":8}},{"generated":{"line":19,"column":11},"source":"anonymous.js","original":{"line":8,"column":15}},{"name":"log","generated":{"line":19,"column":12},"source":"anonymous.js","original":{"line":8,"column":16}},{"generated":{"line":19,"column":15},"source":"anonymous.js","original":{"line":8,"column":8}},{"name":"c","generated":{"line":19,"column":16},"source":"anonymous.js","original":{"line":8,"column":20}},{"generated":{"line":19,"column":17},"source":"anonymous.js","original":{"line":8,"column":8}},{"generated":{"line":20,"column":0},"source":"anonymous.js","original":{"line":9,"column":5}},{"generated":{"line":20,"column":3},"source":"anonymous.js","original":{"line":6,"column":4}},{"generated":{"line":20,"column":5},"source":"anonymous.js","original":{"line":9,"column":7} [...]

2020-01-17 07:17 UTC, milos996 commented on medical institution/PregledSecer.js
> +
ovo ce se moci pristupiti kada instanciras klasu, cisto da znas. Ne postoji mogucnost da ti  napravis private field trenutno u JS.

2020-01-17 07:31 UTC, milos996 requested changes

2020-01-17 07:31 UTC, milos996 commented on medical institution/PregledSecer.js
> +
ovo ce se moci pristupiti kada instanciras klasu, cisto da znas. Ne postoji mogucnost da ti napravis private field trenutno u JS.

2020-01-17 07:31 UTC, milos996 commented on medical institution/pacijent.js
> +    }
ovo ne treba ovdje da se nalazi, njie pacijent odgoovoran da dodaje pacijente od doktora, ovdje ti treba samo `doktor.addPacijent(this)` , u doktor klasi imas metodu addPacijent i tamo dodajes

2020-01-17 07:31 UTC, milos996 commented on medical institution/pacijent.js
> +    }
Ovdje treba da iskoristis polimorfizam, odnosno vise oblika pregleda - jedna metoda, vise implementacija.
Sobzirom da imas `Pregled` klasu koja je parent klasa od `PregledHolesterol ` , `PregledSecer ` i `PregledPritisak `, napravis metodu izvrsi unutar `Pregled` klase, a override-ujes unutar ostalih child klasa i napises njihovu implementaciju.

2020-01-17 07:31 UTC, milos996 commented on medical institution/doktor.js
> +                console.log("[ "+ format(new Date()) +" ] Doktor " + this.getIme() + " zakazuje pregled za merenje holesterola u krvi za pacijenta " + pacijent.getIme());
za logovanje akcija napravi loger koji ce da loguje

2020-01-21 08:11 UTC, merged